src/component/sheet.js

Made MAC delete button compatible

---

src/component/sheet.js

Implemented behaviour of Shift + Tab and Shift + Enter

---

readme.md
src/canvas/draw.js
src/component/sheet.js
src/component/table.js
src/component/toolbar.js
src/data_proxy.js
src/index.js

bugfix #39: Underline text

---

src/canvas/draw.js
src/component/element.js

- Remove the unnecessary variable in 'if' sentence
> 'wrapText' was checked already
- Changed 'if' sentences to 'if-else' sentences for understanding clearly

Improvement: Changed some condition sentences

---

src/core/formula.js

Added new formulae in the drop down menu .

Add New Formulae in Dropdown menu

---

src/component/dropdown_format.js
src/core/format.js
src/locale/en.js

Added Euro currency format in the drop down menu.

Add Euro currency format

---

src/core/cell.js

Previously condition inside IF like IF(3>-2,"y","n") were failing. So added condition to allow that kind of operations.

Added condition to allow If operations like (2>-3).

---

src/canvas/draw.js
src/component/contextmenu.js
src/component/editor.js
src/component/sheet.js
src/component/table.js
src/core/cell.js
src/locale/en.js

Added menu items to the context menu to disable editing of certain cells based on their property. (Individual cells can now be toggled on/off to either lock/unlock cell editing).
Added support for unary negative operator. (For example =-A2).

Disable cell editing functionality

---

.gitignore
src/core/_.prototypes.js
src/core/alphabet.js
src/core/cell.js
src/core/font.js
src/core/format.js
src/core/formula.js
test/core/alphabet_test.js
test/core/cell_test.js
test/core/font_test.js
test/core/format_test.js
test/core/formula_test.js

add "test/core/font_test.js" and enrich some other test cases
add JSdoc to src/core/alphabet.js and some others

add some test cases and add JSdoc to code for better reading

---

src/component/sheet.js

add horizontal scroll support

---

src/component/sheet.js

Fix Mac computer touchpad vertical scroll horizontal scroll bar automatically left.

Bugfix:Mac computer touchpad scrolling

---

src/component/sheet.js

fix autofill error when unselected areas

---

src/core/data_proxy.js

supports setting multiple borders

---

package.json
src/index.d.ts

Hi, master, I am very appreciated for your module. I am using typescript, it would be very grateful  if you could help to add types for this awesome module.

docs: added types for the components

---

src/index.d.ts

sheetIndex and text should be the other way around

Fix type definition for cellText

---

src/core/row.js

Insert a row between row 5 and 9, breaks the formula.

Fixes for inserting row or column breaks the formula.

---

src/component/bottombar.js

Remove strange limit for 10 sheet ( issue https://github.com/myliang/x-spreadsheet/issues/415)

Remove 10 sheets limit

---

src/component/event.js
src/component/sheet.js

1. support custom event recur bind

Added: custom eventEmitter

---

src/component/sheet.js
src/core/data_proxy.js

This commit add coping selected cell range by ctrl+c to The system clipboard too.  Used this API https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText

Copy cell range by ctrl+c to system clipboard myliang/x-spreadsheet#423

---

build/webpack.dev.js
src/core/data_proxy.js

1) navigator.clipboard api available only for 127.0.0.1/localhost or HTTPS protocol. This additional pull request check that api available and open browser on 127.0.0.1
filter copy to system clipboard if api is not available myliang/x-spreadsheet#423
2) Fix column offset in clipboard
3) Fix clipboard format

Fix clipboard format

---

src/core/row.js

fix:issues:#401

---

src/component/editor.js
src/core/row.js

PR for fix in https://github.com/myliang/x-spreadsheet/issues/300

Fix changing disabled cell

---

index.html
src/core/data_proxy.js
src/index.d.ts
src/index.js

Added showBottomBar option

---

src/index.d.ts

Fix return types for 'cellText' / 'loadData' / 'change'

Fix return types

---

src/component/bottombar.js
src/index.js

Related issue https://github.com/myliang/x-spreadsheet/issues/508

fix: bottom bar 'read' mode fixes and rename/delete sheet 'change' event

---

src/component/bottombar.js
src/component/sheet.js
src/core/data_proxy.js
src/index.js

1. support other excel copy and paste
2. fix the compatibility scheme that cannot access the clipboard under http

feat: power paste

---

src/core/alphabet.js

Simplified alphabet `indexAt`

---

docs/index.html
index.html
src/component/sheet.js
src/core/data_proxy.js

Hello,
This is my attempt to add supporting for pasting content from system clipboard. Please let me know what you think.

Paste from clipboard

---

src/component/sheet.js

https://user-images.githubusercontent.com/38180/199268005-256c7070-3c88-4f9b-b11b-8cf72c165882.mov

feat: Resizing multiple rows/cols height/width
